### ISSUE TITLE
silkscreen of C17 and C18 has polarity backwards

### ISSUE THREAD

**Issue by skot** [skot/bitaxe#1]
flip the silkscreen

**Comment by skot** [comment]
Ack, this was correct in v1, so now it's backwards in v2 because of 6d5e3a8. The band on C17 and C18 mark the **positive** side of the capacitor.

<img width="596" alt="image" src="https://user-images.githubusercontent.com/140785/173727415-d6564199-2cfe-4068-97bd-b0f9c145ad92.png">

**Comment by barnix2001** [comment]
Hi! Bitaxe is a great project. Something is wrong about JTAG for ESP32-S3-WROOM-1. 
Your JTAG on PCB is: GPIO9, GPIO12, GPIO13, GPIO14, GPIO21, GPIO47
JTAG for ESP32-S3-WROOM-1 in doc is: IO42,IO41,IO40,IO39
