### ISSUE TITLE
Button footprint too small

### ISSUE THREAD

**Issue by derhaegr** [skot/bitaxe#113]
Including pads it should be at least 5mm
<img width="325" alt="2024_01_12_17_35_01_bitaxeUltra_PCB_Editor" src="https://github.com/skot/bitaxe/assets/13415776/0767b85d-6b60-4030-a168-a109a419fe84">

**Comment by skot** [comment]
Wow, yes you are right. it's not right. from the [datasheet](https://www.citrelay.com/Catalog%20Pages/SwitchCatalog/CS1213.pdf);
<img width="306" alt="image" src="https://github.com/skot/bitaxe/assets/140785/fc47be3b-0ca2-4811-813b-e58605c966fb">

this means the pads should be 1.8x0.9mm and the pad center 2.05mm from the part center.

**Comment by skot** [comment]
correct size on the right; 
<img width="1288" alt="image" src="https://github.com/skot/bitaxe/assets/140785/b0716e16-b8b7-426b-8c0a-4e206ac298c7">
I think I just grabbed a footprint from Ultralibrarian without checking it 😣

**Comment by skot** [comment]
@derhaegr I just pushed a fix. can you double check it?

**Comment by derhaegr** [comment]
@skot Board file seems ok but the gerber has 0.88mm pads or is it just me?
