### ISSUE TITLE
Remove display header in favor of staggered holes 

### ISSUE THREAD

**Issue by benjamin-wilson** [skot/bitaxe#120]
1. The display header pads are relatively small and may rip out when the display is removed. 

2. The exposed bit of the pads are too large and need to be covered with more mask. The large pads cause the header to tilt during reflow, making the screen not parallel/perpendicular. Making them the same height as the pins should make it self-align as well.

**Comment by AxisRay** [comment]
I think using an FPC socket would be better? This way, we can directly attach the screen to the PCB.

**Comment by skot** [comment]
Should we fix this for 205?

I'm not really a big fan of that display connector. It seems too tall and too lose, making the display look wonky often.

I'll take a look at some options.

**Comment by benjamin-wilson** [comment]
The SMD version is significantly snugger in fit - this is why i'm having issues with pads ripping

**Comment by benjamin-wilson** [comment]
![image](https://github.com/skot/bitaxe/assets/1399163/6aec6594-968b-4c17-a0bb-bc57ca840436)
The height seems appropriate as well.
One option to completely eliminate it would be to have staggered holes and insert it directly into the PCB
![image](https://github.com/skot/bitaxe/assets/1399163/76b19242-5fa6-4220-ad1b-055d5937aa6f)

**Comment by AxisRay** [comment]
my solution
I printed a 10mm*10mm*10mm cube and stick it to the pcb.


![image](https://github.com/skot/bitaxe/assets/6546326/4d4f2ee2-0fb6-4d43-823a-2feb3fc7ae18)

**Comment by benjamin-wilson** [comment]
The more I think about it - the best part is no part. The display fits really nice and secure into those staggered holes while being easy to insert/remove. The tube the header comes in is a big pain as well.
