### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by kakawlala** [skot/bitaxe#125]
I made bitaxeUltra 204 on PCWAY. The chip used is BM1366AL. I used esptool to flash esp-miner-factory-204-v2.0.7.bin, but it didn't work and it showed that it could only accept new jobs.  How should I measure whether there is a component failure or misalignment?  Or maybe my programming method is wrong.
The heat dissipation is also normal and there is no high temperature protection.

![P_20240222_160505](https://github.com/skot/bitaxe/assets/89348834/f4188373-73af-423b-8a28-e88a75cf0ebf)
![P_20240222_173054](https://github.com/skot/bitaxe/assets/89348834/e55802f8-99ae-42fe-ac03-c3ad17d31408)
![P_20240222_173031](https://github.com/skot/bitaxe/assets/89348834/7adf7552-a001-4027-a05a-80823726ebe0)
![P_20240222_173402](https://github.com/skot/bitaxe/assets/89348834/4f02f5ae-8254-4ba5-94fa-82daa0d151fe)
![Screenshot_20240222-173528_Chrome_1](https://github.com/skot/bitaxe/assets/89348834/ef2e337f-3298-40b2-b9bc-621a05300332)
![Screenshot_20240222-173609_Chrome](https://github.com/skot/bitaxe/assets/89348834/28393eed-dccf-449f-ba9c-d94006b46df1)
![P_20240222_174431](https://github.com/skot/bitaxe/assets/89348834/89d884f1-0e64-4881-9d16-5f592d22d5c8)

The power supply used is also normal and it works on another bitaxe I purchased online.  But on the finished product produced by PCway, it is observed that the input power is only more than 300 mA, and it should be 3000mA.

![Screenshot_20240222-175125_Chrome (1)_1](https://github.com/skot/bitaxe/assets/89348834/5e0171d2-a85d-42ec-9ff1-c573a57b1fc0)

Fortunately, two of the five devices are working normally, but I don't know how to use the TP point to determine which part of the three faulty devices is faulty.

![P_20240222_210445](https://github.com/skot/bitaxe/assets/89348834/888412e4-4ecb-4918-b998-b335bf88f894)

**Comment by skot** [comment]
Everything looks good but it's not mining sounds like an ASIC issue to me. Likely the ASIC isn't soldered properly, or the chip is bad.

**Comment by skot** [comment]
I'm going to close this as it isnt a bitaxe issue. Can you bring this up on the OSMU Discord? There is an invite link at bitaxe.org

Some other people have attempted PCBWay assembly with similar results.

**Comment by kakawlala** [comment]
> 一切看起來都不錯，但對我來說，這不是挖礦，聽起來像是 ASIC 問題。可能是 ASIC 焊接不正確，或是晶片損壞。

Thanks for your reply, you are right.  After reinstalling BM1366 on the 3 previously faulty devices, there is still no hash value.  Later, after I swapped the chips of a normal and abnormal device, the results were also swapped.  Sure enough, it was a fault with BM1366.

![P_20240223_003649](https://github.com/skot/bitaxe/assets/89348834/d328f6f1-34e7-4e30-bc68-6a08852579ab)
