### ISSUE TITLE
Bitaxe chip 1397

### ISSUE THREAD

**Issue by bamatila** [skot/bitaxe#129]
Hello, i build the bitaxe and flashed trhough the web flasher, then connect it but after entering every information the bitaxe don't work . I got a notification about a low voltage.
![image](https://github.com/skot/bitaxe/assets/162356009/bae455b5-263c-42db-a78c-5799e863af80)

Also i tried to flash it with chip 1366 and i  got this 
![Capture d'écran 2024-03-04 193258](https://github.com/skot/bitaxe/assets/162356009/3d8262ff-a8d2-4077-842d-9ebe1fb71dce)

**Comment by 19201003080114** [comment]
Check:
TP13 = 1.8v
TP14 = 0.8V
TP32 = 1.8v
