### ISSUE TITLE
Panne Bitaxe BM1397 V3.8

### ISSUE THREAD

**Issue by Peichan83** [skot/bitaxe#132]
Bonjour,

Suite à une panne de wifi de mon opérateur et pendant une mise à jour du esp-miner.bin, mon bitaxe ne s'allume plus.

Il est détecté par mon réseau wifi, mais dès que je le sélectionne, cela me mets en échec de connexion.

Le ventilateur tourne mais l'écran lcd ne s'allume plus.

Après un passage à la loupe, aucun composant ne semble HS.

Comment puis-je faire un hard reset ou comment puis-je le reconfigurer svp.

Merci d'avance.

**Comment by bamatila** [comment]
Salut essaie de le reflasher via un pc, prends le bitaxe max puis après tu peux le reconfigurer en te connectant au wifi du bitaxe 

https://www.youtube.com/watch?v=e37tbrXdAtY : tuto 

https://wantclue.github.io/bitaxe-web-flasher/ web flasher

**Comment by Peichan83** [comment]
Re- je veux bien mais j'ai un modèle BM1397 V3.8 sans port usb.
![20240306_220012](https://github.com/skot/bitaxe/assets/98104943/e87a1761-bcc7-4772-8f31-e95681a2b2bb)

Avez-vous une solution de connexion?

**Comment by bamatila** [comment]
AH je ne sais pas bon courage

**Comment by 19201003080114** [comment]
This is not a "legit" Bitaxe so ESP-Miner may not work properly with this hardware.
Since there is no USB, you need to reflash it using the connector next to the display (upper right in your picture) and use this programmer
<img width="429" alt="Untitled 2" src="https://github.com/skot/bitaxe/assets/158797249/e190f730-b3c3-4417-af05-435e134da252">

**Comment by Peichan83** [comment]
Ok J'ai commandé du coup le : 
Esp-Prog Jtag Debug & Programme téléchargement pour carte de développement Esp-Prog Jtag Debug Programme téléchargement compatible avec Esp32.

J'espère pouvoir le re flasher.

**Comment by Peichan83** [comment]
Bonsoir, après avoir reçus, enfin après 1 bon mois d'attente mon esp jtag.

J'ai réussi grâce à vous à flasher mon bitax, seul problème, je n'arrive plus à le paramétrer correctement.

Pouvez-vous m'aider à nouveau?

Cordialement
