### ISSUE TITLE
No Hash

### ISSUE THREAD

**Issue by BKKullerkeks** [skot/bitaxe#136]
Hi guys, I got my Bitaxe Ultra today and have everything set up so far but unfortunately I have a hash of 0. I don't know what to do, do you have any ideas? I have already reflashed the Bitaxe. 

Greetings Kullerkeks

**Comment by 19201003080114** [comment]
Hard to tell what could be wrong without screenshots

**Comment by BKKullerkeks** [comment]
![Unbenannt](https://github.com/skot/bitaxe/assets/163443306/fe772600-796f-456b-b020-c3c3b6089499)

**Comment by BKKullerkeks** [comment]
![bit](https://github.com/skot/bitaxe/assets/163443306/366a9999-0e63-4fe3-82d0-92b08dfe84cf)

**Comment by 19201003080114** [comment]
Wrong pool address and port

https://solo.ckpool.org/

**Comment by BKKullerkeks** [comment]
still the same 0 Hash

**Comment by 19201003080114** [comment]
Address should be "solo.ckpool.org", NOT "de.ckpool.org"
Port should be "3333" unless you want high diff then use "4334"

**Comment by BKKullerkeks** [comment]
its the same 0 hash

**Comment by 19201003080114** [comment]
Did you restart it after saving the changes?

**Comment by BKKullerkeks** [comment]
yes, i think it is maybe a firewall problem

**Comment by BKKullerkeks** [comment]
![fehgl](https://github.com/skot/bitaxe/assets/163443306/ae33ab81-e054-41c0-8d9b-669ea622518c)

**Comment by he4dhuNTeR** [comment]
Wrote your wallet address correctly? Ck checks this at connecting. Also already tried another pool like VKpool or publicpool?

**Comment by BKKullerkeks** [comment]
yes i tried all

**Comment by he4dhuNTeR** [comment]
Just as an offer if you have Telegram, you can search for "BITAXE GERMAN" group, we have some real cracks there for hardware and software, maybe they can help you immediately. And communication is easier on TG.

**Comment by BKKullerkeks** [comment]
thx thats a god idea

**Comment by BBRENESS** [comment]
did you ever find the issue?

**Comment by 19201003080114** [comment]
If you use high diff port, it is normal that it is not working.
