### ISSUE TITLE
SELF TEST FAIL, NO CHIPS DETECTED

### ISSUE THREAD

**Issue by Ivanverdonck** [skot/bitaxe#139]
Hello,

I have my Bitaxe made by PcbWay. But it seems not to be working:

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x28 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4037b8b2
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x16e0
load:0x403c9700,len:0x4
load:0x403c9704,len:0xc00
load:0x403cc700,len:0x2eb0
entry 0x403c9908
I (27) boot: ESP-IDF v5.1 2nd stage bootloader
I (27) boot: compile time Mar  3 2024 19:55:36
I (27) boot: Multicore bootloader
I (30) boot: chip revision: v0.2
I (34) boot.esp32s3: Boot SPI Speed : 80MHz
I (38) boot.esp32s3: SPI Mode       : DIO
I (43) boot.esp32s3: SPI Flash Size : 16MB
I (48) boot: Enabling RNG early entropy source...
I (53) boot: Partition Table:
I (57) boot: ## Label            Usage          Type ST Offset   Length
I (64) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (72) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (79) boot:  2 factory          factory app      00 00 00010000 00400000
I (87) boot:  3 www              Unknown data     01 82 00410000 00300000
I (94) boot:  4 ota_0            OTA app          00 10 00710000 00400000
I (101) boot:  5 ota_1            OTA app          00 11 00b10000 00400000
I (109) boot:  6 otadata          OTA data         01 00 00f10000 00002000
I (117) boot:  7 coredump         Unknown data     01 03 00f12000 00010000
I (124) boot: End of partition table
I (128) boot: Defaulting to factory image
I (133) esp_image: segment 0: paddr=00010020 vaddr=3c0b0020 size=2a954h (174420) map
I (173) esp_image: segment 1: paddr=0003a97c vaddr=3fc98100 size=04bbch ( 19388) load
I (177) esp_image: segment 2: paddr=0003f540 vaddr=40374000 size=00ad8h (  2776) load
I (179) esp_image: segment 3: paddr=00040020 vaddr=42000020 size=a73ech (685036) map
I (310) esp_image: segment 4: paddr=000e7414 vaddr=40374ad8 size=13614h ( 79380) load
I (336) boot: Loaded app from partition at offset 0x10000
I (337) boot: Disabling RNG early entropy source...
I (348) cpu_start: Multicore app
I (348) cpu_start: Pro cpu up.
I (349) cpu_start: Starting app cpu, entry point is 0x40375584
I (0) cpu_start: App cpu up.
I (367) cpu_start: Pro cpu start user code
I (367) cpu_start: cpu freq: 160000000 Hz
I (367) cpu_start: Application information:
I (370) cpu_start: Project name:     esp-miner
I (375) cpu_start: App version:      v2.1.3
I (380) cpu_start: Compile time:     Mar 18 2024 01:00:33
I (386) cpu_start: ELF file SHA256:  458b5eb513f460e4...
I (392) cpu_start: ESP-IDF:          v5.1
I (396) cpu_start: Min chip rev:     v0.0
I (401) cpu_start: Max chip rev:     v0.99 
I (406) cpu_start: Chip rev:         v0.2
I (411) heap_init: Initializing. RAM available for dynamic allocation:
I (418) heap_init: At 3FCA2460 len 000472B0 (284 KiB): DRAM
I (424) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM
I (431) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (437) heap_init: At 600FE010 len 00001FF0 (7 KiB): RTCRAM
I (444) spi_flash: detected chip: gd
I (447) spi_flash: flash io: dio
W (452) ADC: legacy driver is deprecated, please migrate to `esp_adc/adc_oneshot.h`
I (460) sleep: Configure to isolate all GPIO pins in sleep state
I (467) sleep: Enable automatic switching of GPIO sleep configuration
I (474) app_start: Starting scheduler on CPU0
I (479) app_start: Starting scheduler on CPU1
I (479) main_task: Started on CPU0
I (489) main_task: Calling app_main()
I (529) miner: NVS_CONFIG_ASIC_FREQ 485.000000
I (529) miner: ASIC: BM1366
I (529) self_test: I2C initialized successfully
I (529) DS4432U.c: Set ASIC voltage = 1.200V [0xC6]
I (539) DS4432U.c: Writing 0xC6
I (539) self_test: OLED init success!
I (559) DS4432U.c: DS4432U+ OUT1 = 0xC6
I (559) serial: Initializing serial
I (559) bm1366Module: Initializing BM1366
I (1769) bm1366Module: 0 chip(s) detected on the chain
final refdiv: 2, fbdiv: 233, postdiv1: 6, postdiv2: 1, min diff value: 0.416656
I (1799) bm1366Module: Setting Frequency to 485.00MHz (0.01)
I (1799) self_test: 0 chips detected
I (1799) bm1366Module: Setting max baud of 1000000 
I (1819) serial: Changing UART baud to 1000000
I (2819) self_test: Sending work
E (2819) self_test: SELF TEST FAIL, NO CHIPS DETECTED

Is there a way to test if the chip is OK? Is someone having the same issue?

Kind regards.

**Comment by skot** [comment]
This seems like a build issue. Probably the ASIC solderin. Can you please bring this up on the OSMU discord help channel? https://osmu.bitaxe.org
