### ISSUE TITLE
Pads size mismatch between F.Paste and F.Mask on U9

### ISSUE THREAD

**Issue by 3x3y3z3t** [skot/bitaxe#153]
See picture for reference.
U9 is the only component that got this issue.

It may not be an issue for hand assemble, but for PCBA order PCBWay have raised question about this ([discord message](https://discord.com/channels/1091348375301013615/1224531849280491610/1228010694838976532)).

![image](https://github.com/skot/bitaxe/assets/16525687/0357e04a-4050-4cb1-b8fc-b1a5620c2624)

**Comment by skot** [comment]
We changed the U9 stencil to this a while back and it seems to have helped a lot with hand assembly.

**Comment by benjamin-wilson** [comment]
This has since been reverted
![image](https://github.com/skot/bitaxe/assets/1399163/f464d96e-f4ab-49b6-8359-f7269390e5c7)
