### ISSUE TITLE
Change Buck to TPS546D24ARVFR

### ISSUE THREAD

**Issue by benjamin-wilson** [skot/bitaxe#154]
https://webench.ti.com/appinfo/webench/scripts/SDP.cgi?ID=42BF472B95D37383

17A should be sufficient, changing to this buck should allow removal of INA260, DS4432U and EMC2101.

**Comment by weixiongmei** [comment]
@benjamin-wilson  what's minimum current does the BM1366 needs?

**Comment by skot** [comment]
added in b9c48b8
