### ISSUE TITLE
Change Barrel Plug Jack to 54-00164/DC050-T

### ISSUE THREAD

**Issue by benjamin-wilson** [skot/bitaxe#158]
While the PJ-036AH-SMT-TR has lots of stock on DigiKey, it's expensive ($1.01900 vs $0.62620), experiences issues during reflow where the 3rd leg does not make contact and has a large, unusual footprint. 

The 54-00164 has more limited availability but is widely available on LCSC https://www.lcsc.com/product-detail/DC-Power-Connector_SHOU-HAN-DC050-T_C431534.html bagged for $0.072 (verified correct size on datasheet and in-hand despite incorrect listing)

**Comment by skot** [comment]
the 54-00164 footprint in the bitaxe library was corrupt. I grabbed a new one from Digikey / SnapEDA
