### ISSUE TITLE
Test point value

### ISSUE THREAD

**Issue by tdcaot** [skot/bitaxe#162]
I'm currently own a supra 400 and have power test fail, can you provide "normal" test point values or information ? Thanks.

**Comment by skot** [comment]
Please use the help channel on the OSMU Discord for support. discord.gg/osmu

**Comment by tdcaot** [comment]
> > I'm currently own a supra 400 and have power test fail, can you provide "normal" test point values or information ? Thanks.
> > Maybe your core_voltage is not between 1100mV and 1300mV after flashing. Then a power fail error is shown.
> 
> You can flash firmware without self test. Use the line "selftest,data,u16,0" in the config.cvs and flash. If your miner starts, you may be able to read the values in the webui.

Thank so much. I was able to bypass the self-test. Now it works fluently.
