### ISSUE TITLE
402: TPS546D24A BP1V5 & DRTN connection

### ISSUE THREAD

**Issue by manan1199** [skot/bitaxe#164]
DRTN is internally connected to the ADNG and does not seem to work with the I2C configuration.

**Comment by manan1199** [comment]
The MSEL & VSEL also needs to be connected to the resistance divider between BP1V5 and AGND

**Comment by skot** [comment]
Ah! good catch.

**Comment by skot** [comment]
<img width="711" alt="image" src="https://github.com/skot/bitaxe/assets/140785/ddd455e4-6a73-4031-b778-264ea7612617">
