### ISSUE TITLE
 402 - R2,R3 and R4

### ISSUE THREAD

**Issue by Alexgtc** [skot/bitaxe#178]
In the gabers come the resistors r2,r3 and r4 but the list of materials do not come. Do you know if they are necessary and if so, what value do they have to have

**Comment by 19201003080114** [comment]
If not in BOM, assume DNP

**Comment by Alexgtc** [comment]
What is DNP? Do you mean that if it's not on the list, don't put them? Would it work well then without putting those resistances?

**Comment by 19201003080114** [comment]
DNP is Do No Populate. You leave them empty. 
If you want to be sure, check the schematics.

**Comment by Alexgtc** [comment]
Where can you find the diagrams of the supra 402 bitaxe plate?

**Comment by 19201003080114** [comment]
https://github.com/skot/bitaxe/tree/supra-402

402 is not ready. Yes 401

**Comment by Alexgtc** [comment]
What is missing from the plate to be finished? With the current bom list and the current gabers it doesn't work?

**Comment by skot** [comment]
Please only use issues for bugs. For assembly help please ask on the OSMU Discord
