### ISSUE TITLE
Supra stops hashing 

### ISSUE THREAD

**Issue by M31andromeda** [skot/bitaxe#183]
So I've built 6 Supras so far. While 4 of them are working as expected, 2 of them always stop hashing shortly after power-up. WiFi connection is there. I've also replaced the ASIC on one unit but the issue persists. Not sure where else I should look. Any ideas? 

<img width="982" alt="Screenshot 2024-09-08 163639" src="https://github.com/user-attachments/assets/d019251f-5c4a-4027-886b-bc7f1d220358">

**Comment by M31andromeda** [comment]
Running longer now but operation is not looking right...

<img width="986" alt="Screenshot 2024-09-08 190231" src="https://github.com/user-attachments/assets/6d37aa5d-a67e-4953-a511-187a6ad2d7e8">

Screenshot of another Supra working as it should:

<img width="987" alt="Screenshot 2024-09-08 190302" src="https://github.com/user-attachments/assets/c1bc05e2-4225-4c98-9d4f-c55892483a54">

**Comment by benjamin-wilson** [comment]
On your second post that looks like normal operation, averaging to the expected hashrate.
