### ISSUE TITLE
Bitaxe supra self test monitor fail

### ISSUE THREAD

**Issue by MabsHA** [skot/bitaxe#192]
my bitaxe wasn’t hashing anymore after i installed the 2.2.2 firmware i downgraded to the 2.1.10 still didn’t work. i reflashed with the webflasher New Bitaxe Supra: Board Version 401 (factory)V2.1.10 but now i get message (monitor fail) after self test with serial readings i get this message (self_test: INA260 test failed!) ill ad log download.

any ideas?
[esp-web-tools-logs.1.txt](https://github.com/user-attachments/files/17379525/esp-web-tools-logs.1.txt)

**Comment by 19201003080114** [comment]
Likely you have a hardware failure, and not software related.

**Comment by MabsHA** [comment]
> Likely you have a hardware failure, and not software related. 

Can it be fixed?

**Comment by MabsHA** [comment]
> > Can it be fixed?
> 
> 
> 
> Replace U8, INA260

That's only €2,50 I'll try

**Comment by skot** [comment]
Github issues are not for build issues. please use OSMU.

**Comment by MabsHA** [comment]
Where can I find that?

**Comment by skot** [comment]
https://discord.gg/osmu

**Comment by MabsHA** [comment]
And I didn't know if it was firmware or hardware sorry
