### ISSUE TITLE
SELF TEST FAIL, INCORRECT CORE VOLTAGE

### ISSUE THREAD

**Issue by sospcie** [skot/bitaxe#198]
Hi All,

Finally I was able to build my Bitaxe Gamma device with BM1370BC. Was not easy but was fun. :)

Flashed the firmware, display working, fan spinning, logs display the chip detected, but then I get this message on screen and in the terminal as well

self_test: SELF TEST FAIL, INCORRECT CORE VOLTAGE

Does anyone can give me a hint which of the chip responsible for the CORE VOLTAGE?

Thank you

**Comment by 19201003080114** [comment]
<img width="630" alt="image" src="https://github.com/user-attachments/assets/1c17d63b-4cdf-48de-81ca-e9f815c95e80">

**Comment by benjamin-wilson** [comment]
Github is not the right place for troubleshooting individual issues, this is for fundamental issues with the project.

Visit https://discord.gg/osmu for help.
