### ISSUE TITLE
Heatsink mounting holes are not quite correct

### ISSUE THREAD

**Issue by skot** [skot/bitaxe#2]
they need to be spaced a little further apart.

**Comment by robomaniac** [comment]
You could have one of those holes slotted.

**Comment by skot** [comment]
When I first laid out this board the heatsinks hadn't arrived from China yet. They're here now, and it looks like the holes should be 58.5mm apart. (kinda random)

**Comment by skot** [comment]
the 58.5mm spaced holes work like a charm.
