### ISSUE TITLE
Troubleshooting BitaxeMax 2.3

### ISSUE THREAD

**Issue by Lysnyt** [skot/bitaxe#208]
Hello guys, i believe someone can help me to figure this out.
I tried to assemble the second bitaxe - bitaxe max with bm1397. 

I can´t get it to work, i have tried many firmware versions from 2.1.1 to latest 2.4.1.
I have tried default mining pool for troubleshooting (i dont know if there is any password, i typed "x")
But i get from the realtime log everytime "₿ (57233) bm1397Module: return null"
The BM1397 was new, i have 5 others bitaxe max with same error, with differnet completely new BM1397.
Voltage ok > 5V > 3.3V >1.8V > 0.8V. 
I have registered huuuge voltage drop (0,8V like there was a diode)on input after start. I have Riden 18A 60V power supply.
If i raise the voltage to 5.8V, so it will show 5V voltage in the web interface, i´m worrying about INA260 which has in datasheet supply voltage to 5.5V. 

Workaround:
Bitaxe Max, which was outdated every since a no one did any update to final design (that one with usb connector). 
First i did assemble the outdated version 2.3 without usb connector, which was pain in the ass, as i wanted to upload the firmware with standard usb to ttl bridge (which are we using in work). Somehow i managed to get it done (that it was no webflasher), but nothing worked (no connection). I am electrician, very bad one, but i can do many simple things and i understand basics. We have used in work essemtec pick and place machine, we do industrial measuring devices (level sensors, thermometers, pressure,..) with mainly 0603 parts, so this 0402 parts in big DPS with dozen of space get me no sense. In my point of view, the design is oriented as developing board, as there are dozens TPoints, 2 JTag and another 2 rows of VIAs for future use.. Skot as father of this project did great work, but maybe it is time to make it more simple if there is will.
In the way of the assembly i see flaws like incomplete BOM list (capacitors without voltage requirements, inductance without specifications, outdated github page for any branch, no wiki for troubleshooting or "how to", ..
Many times i have time to help You with this (and i believe other people too) and update anything wrong i get upon, but there is now instruction how to do it. 

Log:
₿ (57233) bm1397Module: return null
₿ (64663) stratum_task: rx: {"params":["67444bb00000e114","e15c9930d787926e5218d5e966591831743546170000a1790000000000000000","01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff3503db580d0004245f5d670473bbfb080c","0a636b706f6f6c112f736f6c6f2e636b706f6f6c2e6f72672fffffffff03a16e9a1200000000220020984a77c289084ff2d434c316bdada021c6c183d507c8a20d3b159b09ac02fe28473161000000000016001451ed61d2f6aa260cc72cdf743e4e436a82c010270000000000000000266a24aa21a9ed9054f8df3080516fc74e7be17f6102b7fddd45033198b0771cf9ce8b113d4dc200000000",["898eb5e1fee3a67fab7b9dc2c3cb829f6b4de8475d25c93af1a476ee622df497","5064f033c5b0fd0f42b2f7d99ea39c53f2f6bee8800ed037e9d1e0070928655c","01d69b652f31b7b62ef94bee1175eb93b11585821766bb81f8e7921f132b6bb1","a001a7a9f55aa2b347746efe7de27cbf96f581d789af264b3091a3996bc7c597","b0bb88f12e2f7c1c0e89d82dc4c027aab2f9708c7d3db104645a9b965becad60","4acb5297a9fdaf688558d4ccd88814b92e2a7324149028cc91e026c502498421","5220f1c12b8e280b628bee2bf8f727be2ee5064243ea3f5450766928ef30f06b","9adde7cb903d82c44ac4f93157f1945f7d9d5226bc3c5f6f8372ed993ce2854e","7a227f7f7f37153f6e7022a664c8c5454352c19c8b5624521c163e642a7c89ea","eaf00f4848d051780566467c419202886aa9d06a959c9c8873ccba5b7a54cc31","e3a256026b32739192dc9bc80a18fcd1574a8a4be42bd827f2ee49361b302e9b","26a682cb5a7cb36b7652e083ac75929ae77239473220ccbb96b723236864d54d"],"20000000","1702b563","675d5f24",false],"id":null,"method":"mining.notify"}
₿ (64793) create_jobs_task: New Work Dequeued 67444bb00000e114
₿ (64793) create_jobs_task: Job processed and queued: 67444bb00000e114
₿ (67233) bm1397Module: return null
₿ (77233) bm1397Module: return null
₿ (87233) bm1397Module: return null
₿ (94743) stratum_task: rx: {"params":["67444bb00000e115","e15c9930d787926e5218d5e966591831743546170000a1790000000000000000","01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff3503db580d0004425f5d670444bf90080c","0a636b706f6f6c112f736f6c6f2e636b706f6f6c2e6f72672fffffffff038c669b1200000000220020984a77c289084ff2d434c316bdada021c6c183d507c8a20d3b159b09ac02fe28563661000000000016001451ed61d2f6aa260cc72cdf743e4e436a82c010270000000000000000266a24aa21a9edddf94460917031e52a5d85e90bd03fa8ee6a2bdd56be65b53ded7d252647656400000000",["898eb5e1fee3a67fab7b9dc2c3cb829f6b4de8475d25c93af1a476ee622df497","5064f033c5b0fd0f42b2f7d99ea39c53f2f6bee8800ed037e9d1e0070928655c","01d69b652f31b7b62ef94bee1175eb93b11585821766bb81f8e7921f132b6bb1","a001a7a9f55aa2b347746efe7de27cbf96f581d789af264b3091a3996bc7c597","b0bb88f12e2f7c1c0e89d82dc4c027aab2f9708c7d3db104645a9b965becad60","e3ad9f87b16a90f628d8a14a18717becbee98b553682aa8a47251e7ca4e63754","0b70f8375beac0720e46d777d60b669fd10b3252b47343cfe3561e5e1d1e3125","2791767860cef67ec985fa5aec53eda6e6d40c5eefb1f0ebafed091536f02191","4b0fddf9dcae6787c95c959dfdb5ea08eec6a1aef4e07743fa2cb0e1c89deb89","42e58ac77c5894b0ac041dc7bb666492142c0e362f77dda07bd70a67ebabee3a","1fdbdcf3ee74e1027348524e888b12778ff9dd9c45989eeff647972a2de1e9a4","40984bd983cb94fd7933845d040ff720663041d45b0d13bf6b90f4e5d693cfdf"],"20000000","1702b563","675d5f42",false],"id":null,"method":"mining.notify"}
₿ (94893) create_jobs_task: New Work Dequeued 67444bb00000e115
₿ (94893) create_jobs_task: Job processed and queued: 67444bb00000e115
₿ (97233) bm1397Module: return null
₿ (107233) bm1397Module: return null

**Comment by skot** [comment]
please use the discussions or (preferably) [OSMU](discord.gg/osmu) for troubleshooting.
