### ISSUE TITLE
Noob Question

### ISSUE THREAD

**Issue by StarGateMiner** [skot/bitaxe#47]
I came across the project, but not fully understanding if right now its something a every day person can replicate, I was looking at the guide, can buy the stuff from Aliexpress but missing the board, are you planning to make and sell the boards. Just some background would be good, thanks..

**Comment by DobQA** [comment]
@skot

**Comment by ralphdesktop** [comment]
I am not Skot but I think I can answer to your question. Everyone could replicate this great project, but you have to buy equipment + to take some time to learn about soldering basics and to understand how it properly works. About the board, you have to contact a PCB manufacturer yourself. More details about that here : https://github.com/ralphdesktop/bitaxe/blob/master/building.md

Have a nice day
