### ISSUE TITLE
Collection for ESP coder 

### ISSUE THREAD

**Issue by Lysnyt** [skot/bitaxe#51]
Hi Skot,

I suggest making a collection for ESP32 programer / coder, as I see this is the primary delay in your big project.
It would be dangerous to send money to someone unknown, as there are many scammers.But if you know someone trustfully enough, we (all who want to contribute with any amount of money) can pay a bill for him to code a ESP miner for you and so for us too.

**Comment by skot** [comment]
Hey @Lysnyt !

The esp-miner is pretty much complete. Check out the nonce-checking branch. We are going to merge with master and release this very soon.

**Comment by Lysnyt** [comment]
Nice to hear it ! :)
