### ISSUE TITLE
C21 silkscreen missing

### ISSUE THREAD

**Issue by skot** [skot/bitaxe#53]
<img width="510" alt="image" src="https://github.com/skot/bitaxe/assets/140785/cc561bab-3396-4520-b216-c6d9bacb1ab6">

**Comment by skot** [comment]
addressed in v1.1

**Comment by shufps** [comment]
I wondered why 0402 everywhere ... on my HAT I replaced the components to be min 0805 for easier manual soldering

**Comment by skot** [comment]
0402 is a lot better than the 0201 on the XP hashboard!
