### ISSUE TITLE
Add copper layer ASIC alignment markers

### ISSUE THREAD

**Issue by skot** [skot/bitaxe#62]
aligning the ASIC for soldering is still hard AF. You can't really use the silkscreen markings because the registration between silk and copper is different for every board run.

Maybe we can use a copper layer mark for alignment?

**Comment by benjamin-wilson** [comment]
I worry that the marks are going to be added to stencils when people order them. jlpcb had to ask me if the tag-connect pads were supposed to be masked.

**Comment by skot** [comment]
I don't think we have room in copper to do it anyways

**Comment by shufps** [comment]
You can easily "draw" copper lines on your PCB. They are not included in the stencils.

**Comment by skot** [comment]
I started looking at this and got a little overwhelmed with finding room for alignment marks on the top copper layer.
