### ISSUE TITLE
Change micro usb USB connector to USB-C

### ISSUE THREAD

**Issue by benjamin-wilson** [skot/bitaxe#64]
Needs no explanation I think :)

**Comment by RndUsername** [comment]
@smartm0use The naming in this repo is very confusing: The "ultra" tag, added bei benjamin-wilson is for the [bitaxe **ultra**](https://github.com/skot/bitaxe/tree/ultra-v1.1) , wich uses the BM1366 ASIC as a mining chip. So there is currently no usb connector for the bitaxe on the main branch.

**Comment by skot** [comment]
this is fixed in v1.1
