### ISSUE TITLE
Replace power connection with 2.1ID 5.5OD barrel connector

### ISSUE THREAD

**Issue by benjamin-wilson** [skot/bitaxe#65]
Most 5v power supplies available come with a 2.1ID 5.5OD barrel connector. This will reduce the amount of work to get a bitaxe working and provide a little protection against shorting.

When creating the connector large pads should be also made underneath if possible so that the connector can be de-soldered and wires can be soldered directly to the PCB for other projects.

**Comment by benjamin-wilson** [comment]
Cost effective candidate:  https://www.digikey.com/en/products/detail/tensility-international-corp/54-00127/9685436

**Comment by skot** [comment]
this is fixed in v1.1
