### ISSUE TITLE
Fan and heatsink specification

### ISSUE THREAD

**Issue by smartm0use** [skot/bitaxe#75]
Can you add these info to README file?

**Comment by skot** [comment]
it's already there: https://github.com/skot/bitaxe#hardware

**Comment by smartm0use** [comment]
There I can read that I can buy a "[40x40mm heatsink and 5V fan](https://www.aliexpress.com/item/2251832861666365.html)":

![image](https://github.com/skot/bitaxe/assets/5399265/c004cb16-f238-4211-af48-69a6e932212a)

Then, I read "Noctua NF-A4x10 5V 4-Pin fan".

So, I deduce that I can buy a 4-Pin fan... but there is not 4-Pin fan in the Aliexpress link.

What's wrong? The link or the 4-Pin information?

**Comment by smartm0use** [comment]
In addition, I see that it is possible to get a fan from a random seller on Aliexpress, otherwise get a Noctua fan. I saw that Aliexpress fans has more or less the same characteristics, especially in terms of rpm and db, but costs 1/3 or even 1/4.
I was wondering if I opt for a cheap fan and then maybe it spins more slowly, stops or has problems cooling, in short, if it doesn't manage to cool properly, what happens?
Does the ASIC chip burn out or does some sensor come into play so bitaxe is saved?

**Comment by skot** [comment]
we are working on some firmware to shut down the ASIC and/or power in an over-temp situation. Currently there is no protection. 

This is going to be a firmware fix, so I'll close this issue.

**Comment by smartm0use** [comment]
Ok, I see. Thank you for the information.
What about the other questions?
Is that Aliexpress link misleading?

**Comment by skot** [comment]
the bitaxe is compatible with 5V fans, either 2-pin, 3-pin or 4-pin.
