### ISSUE TITLE
BOM: R16 value mismatches value of related component

### ISSUE THREAD

**Issue by smartm0use** [skot/bitaxe#80]
In the [BOM file](https://github.com/skot/bitaxe/blob/master/Manufacturing%20Files/bitaxeMax%20BOM.xlsx) this is the row related to R16:

```
Qty          Ref Des          Value          DK                 PARTNO                 DNP
1            R16              80k            311-80.6KLRCT-ND   RC0402FR-0780K6L
```

It says the value is "80 k" but going to see the related component (RC0402FR-0780K6L) its value is 80.6 k.

Is the reported value in the BOM wrong?

**Comment by skot** [comment]
you can't get 80.0k resistors. I've updated the schematic to say the closest value, 80.6k
