### ISSUE TITLE
ninja failed with exit code 1. Halp, I'm dead in the water when attempting to Flash my axe

### ISSUE THREAD

**Issue by dgbitaxe** [skot/bitaxe#93]
ninja failed with exit code 1

[Flash Log.pdf](https://github.com/skot/bitaxe/files/13283690/Flash.Log.pdf)

**Comment by skot** [comment]
You can get help with esp-miner on the OSMU discord; https://discord.gg/9hpKxTbB

(but it looks like you don't have ESP-IDF 5.1 installed)

**Comment by dgbitaxe** [comment]
mikefierke@Mikes-MacBook-Pro esp-idf % idf.py --version             

ESP-IDF v5.2-dev-3775-gb4268c874a

Do I need to revert to 5.1?
